import 'package:isar/isar.dart';

part 'medicine.g.dart'; // generated by `dart run build_runner build`

/// Core Medicine record. `name` is indexed for fast prefix + full-text
/// search (Isar IndexType.value with caseSensitive:false gives us
/// millisecond search even on large inventories).
@collection
class Medicine {
  Id id = Isar.autoIncrement;

  @Index(type: IndexType.value, caseSensitive: false)
  late String name;

  late String company;
  late String batchNumber;
  late DateTime expiryDate;
  late int quantity;
  late double purchasePrice;
  late double salePrice;

  /// Optional shelf location, e.g. "Rack A2" — surfaced during
  /// Scan-to-Sell so staff can find the item fast.
  String? rackLocation;

  /// V2 compliance: flags a controlled medicine that requires CNIC capture
  /// at time of sale.
  bool isControlled = false;

  DateTime createdAt = DateTime.now();
  DateTime updatedAt = DateTime.now();
}
